/**
 * API request/response types for the future POST /api/interview route.
 * The route itself is implemented in a later milestone; these types reference
 * the runtime and LLM output types so the route can be built on them.
 */
import type { InterviewMessage } from "@/types/interview";
import type { AnswerEvaluation, GeneratedQuestion } from "@/types/llm";

export interface InterviewRequest {
  /** Present on the start request. */
  candidateId?: string;
  /** Present when continuing an existing session. */
  sessionId?: string;
  /** Candidate answer to the current question (continue requests). */
  answer?: string;
}

export interface InterviewResponse {
  sessionId: string;
  /** Natural-language question generated by the LLM service. */
  question?: GeneratedQuestion;
  /** Per-answer assessment produced by the evaluator. */
  evaluation?: AnswerEvaluation;
  /** Raw transcript message when present. */
  message?: InterviewMessage;
  /** Whether the interview has answered every planned question. */
  completed: boolean;
}
